### PR TITLE
Added helpful prevention section

### PR DESCRIPTION
**Pull request by OrsosAdam**
Given the "rant" nature of the repository (which I highly respect!)

I added a prevention section, so it wouldn't be 100% rant

### CODE REVIEW

**Comment by swingcake** [comment]
Hi,
Thanks for the PR. I've included some contributing guidelines, please include that and I'll merge.

**Review by swingcake — CHANGES_REQUESTED** [review]
I've included some [contributing guidelines](https://github.com/swingcake/Hacktoberfest-spam/issues/2#issuecomment-537350324), please make the changes accordingly.

**Comment by OrsosAdam** [comment]
I've done the change request! :D

**Review by swingcake — APPROVED** [review]
Good work!

**Pull request merged**
